### ISSUE TITLE
Multiple Muses?

### ISSUE THREAD

**Issue by antonello87** [bardiabarabadi/uvicMUSE#11]
Hi,
do you think it would be possible with the current implementation to connect more than one muse to the same computer?
For example, if I run the GUI two times does it connect to two different Muses or the first one connected locks the BT adapter?

Thanks

**Comment by bardiabarabadi** [comment]
Hello,

That's a good question actually. I haven't tried it yet, but it shouldn't be a problem. Take a look at this issue from bleak (BLE backend that we are using). I will try it in a couple of days, but let me know here if you have already tried it.

[Link to the bleak's issue](https://github.com/hbldh/bleak/issues/345)

**Comment by antonello87** [comment]
Hi @bardiabarabadi,
I tried to connect two Muses by using 2 instances of the GUI and it worked. The only thing I noticed is that sometimes one of the two muses disconnected  after 15/20 minutes. 
Have you already experienced this behaviour? Do you think there is a maximum time after which the Muse disconnects? Which was your maximum recording time? Could it be related to the battery level?
One of them was actually a MuseS and it connected without the need of any modification. 
Does it sound strange to you?
Sorry for the many questions ;)
Thanks
