### ISSUE TITLE
EEG Readings

### ISSUE THREAD

**Issue by CrazyDave4** [bardiabarabadi/uvicMUSE#17]
Hi, I have correctly set it up and can get EEG readings in MatLab. Now I'm curious what do the five fields of EEG samples represent - are they channels or alpha, beta, gamma, theta, delta for a specific channel? Thanks!

**Comment by bardiabarabadi** [comment]
The channels pass through the raw samples. To get alpha/beta/... channels you need to filter the signals and limit their bandwidth. See this for more information:
https://nhahealth.com/brainwaves-the-language/

**Comment by CrazyDave4** [comment]
Thank you so much for the quick reply! Just to confirm since there are five fields for EEG readings do they represent the channels: AF7, AF8, TP9, and TP10 respectively (there are only four channels though)? Sorry for the naive question as I'm only a beginner in BCI...
