### ISSUE TITLE
LSL stream with MuseWrapper?

### ISSUE THREAD

**Issue by antonello87** [bardiabarabadi/uvicMUSE#9]
Could the LSL stream be added to the Python library implementation?  

P.s. Thanks a lot for this wonderful work!!

**Comment by bardiabarabadi** [comment]
Hello,

Done, I added it to the both branches (dongle and master). Haven't got the time to try it out yet. Please let me know if there is an issue with it.

P.S. sorry about the delay. It has been a busy year so far.
